# Generated by Django 5.0 on 2023-12-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('type_of_comp', models.CharField(choices=[('IT', 'IT'), ('Agri', 'Agri'), ('Food', 'Food'), ('Cosmetics', 'Cosmetics')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
