# Generated by Django 5.0 on 2023-12-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_company_updated_at_alter_company_created_at_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CompanyUser',
        ),
    ]
