# Generated by Django 5.0 on 2023-12-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_rename_user_companyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
