# Generated by Django 5.0 on 2023-12-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_company_company_logo_companyuser_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/company_logos/'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/user_images/'),
        ),
    ]
